meta_product_name: "Pacifico"
meta_title: "Pacifico | Find the best Asian food in the city!"
meta_description: "A directory of top-notch Asian delights in Montreal"
meta_image: "project_pacifico.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
