meta_product_name: "MTL Oriental"
meta_title: "MTL Oriental | Find the best Asian food in the city!"
meta_description: "A directory of top-notch Asian delights in Montreal"
meta_image: "project_mtloriental.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
